apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  labels:
    k8s-app: metrics-server
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      labels:
        k8s-app: metrics-server
    spec:
      containers:
      - name: metrics-server
        image: registry.k8s.io/metrics-server/metrics-server:v0.6.4
        args:
        - --cert-dir=/tmp
        - --secure-port=443
        - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
        - --kubelet-insecure-tls
        ports:
        - containerPort: 443
          name: main-port
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  labels:
    k8s-app: metrics-server
spec:
  selector:
    k8s-app: metrics-server
  ports:
  - port: 443
    targetPort: main-port
